#!/bin/bash
java -jar strange.jar \
	pair \
	$( dialog \
		--title "First File" \
		--stdout \
		--title "Please choose first file" \
		--fselect \
		/home/ \
		0 0 \
	) \
	$( dialog \
		--title "Second File" \
		--stdout \
		--title "Please choose second file" \
		--fselect \
		/home/ \
		0 0 \
	) \
	java \
	index.html

/data/data/com.termux/files/usr/bin/termux-open http://127.0.0.1:8000

sudo apt install python3

python3 \
	-m http.server 8000 \
	--bind 127.0.0.1 \
	--directory .
